substitutions:
  _APP: admin
  _REGION: asia-northeast1

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

steps:
  - id: deploy-hosting
    name: node:20
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        npm install -g firebase-tools@latest --silent --no-audit --no-fund
        firebase deploy --only hosting \
          --project=$PROJECT_ID \
          --config=apps/${_APP}/firebase.json \
          --non-interactive
